### ISSUE TITLE
Chart: styling: the shadow text makes it quite difficult to read the bullet points (wet bulb chart)

### ISSUE THREAD

**Issue by lpicci96** [ONEcampaign/DataDive_Climate#25]
Story id: 1628179
Chart: Wet bulb chart in climate datadive

Label outline issue. Resolved by reducing outline size and changing color

**Comment by lpicci96** [comment]
@jm-rivera Flourish stories don't allow you to change the label outline size, and changing the color make it more difficult to read

**Comment by jm-rivera** [comment]
I think this version is ok, but I suppose the other option would be to make those labels white. What do you think? Any preference? @lpicci96 


![Image](https://user-images.githubusercontent.com/7374450/197475855-f17b635d-02a3-4d15-9f18-fd7d0fb608f2.png)

**Comment by lpicci96** [comment]
all white text will be harder to read In my opinion so prefer the current version

**Comment by jm-rivera** [comment]
Let's keep that then! @lpicci96
